version: '3'

services:
  # Application

  app:
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"

  postgres:
    image: 'bitnami/postgresql'
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=deliveries
    volumes:
      - 'postgresql_data:/bitnami/postgresql'

volumes:
  postgresql_data:
    driver: local